language: c

sudo: false

services:
  - postgresql
  - mysql

addons:
  postgresql: "10"
  apt:
    packages:
      - libgmp-dev
      - postgresql-client
      - postgresql-server-dev-all

env:
 - GHCVER=8.2
 - GHCVER=8.4
 - GHCVER=8.6

install:
  - export STACK_YAML=stack-$GHCVER.yaml
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack --version
  - echo "CREATE USER esqutest WITH PASSWORD 'esqutest';" | psql postgres
  - createdb -O esqutest esqutest
  - mysql -e 'CREATE DATABASE esqutest;'

script:
  - stack setup
  - stack update
  - stack build
  - stack test
  - cd test/expected-compile-failures/
  - bash test.sh

cache:
  directories:
  - $HOME/.stack
