language: c

sudo: false

services:
  - mysql

addons:
  postgresql: "10"
  apt:
    packages:
      - libgmp-dev
      - postgresql-10
      - postgresql-client-10
      - postgresql-server-dev-all

env:
  - GHCVER=8.2 PGPORT=5433
  - GHCVER=8.4 PGPORT=5433
  - GHCVER=8.6 PGPORT=5433

install:
  - export STACK_YAML=stack-$GHCVER.yaml
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack --version
  - mysql -e 'CREATE DATABASE esqutest;'

before_script:
  - psql -U postgres -c "CREATE USER esqutest WITH PASSWORD 'esqutest';"
  - createdb -O esqutest esqutest

script:
  - stack setup
  - stack update
  - stack build
  - stack test
  - cd test/expected-compile-failures/
  - bash test.sh

cache:
  directories:
  - $HOME/.stack
